sudo: required

services:
  - docker

language: python

script:
  - python -m pytest -v
#  - docker-compose build
#  - docker-compose run test

after_success:
  - sh .travis/deploy_dockerhub.sh
#  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh